name: Docker Build

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  docker-build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Build Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: false
        tags: github-actions-demo:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max
        
    - name: Test Docker image
      run: |
        echo "Testing Docker image..."
        # Build image locally for testing
        docker build -t github-actions-demo:test .
        
        # Test if image runs
        docker run --rm -d --name test-container -p 3001:3000 github-actions-demo:test
        
        # Wait for container to start
        sleep 5
        
        # Test health endpoint
        curl -f http://localhost:3001/health || exit 1
        
        # Clean up
        docker stop test-container
        echo "✅ Docker image test passed!"
