name: Railway Auto Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

jobs:
  deploy:
    name: Deploy to Railway
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run tests
      run: npm test
      
    - name: Install Railway CLI
      run: npm install -g @railway/cli
      
    - name: Login to Railway
      run: |
        echo "🔐 Logging into Railway..."
        echo "${{ secrets.RAILWAY_TOKEN }}" | railway login
        echo "✅ Logged in successfully!"
        
    - name: Deploy to Railway
      run: |
        echo "🚂 Deploying to Railway..."
        railway up --detach
        echo "✅ Deployment completed!"
        
    - name: Get deployment info
      run: |
        echo "🔗 Getting deployment information..."
        railway status
        echo "✅ Check Railway dashboard for deployment URL"
